title: Java, Maven, FirstSpirit & More
description: >
  This is a collection of small OpenSource projects related with my work as software
  developer.
author: Marian Zaplatynski
theme: jekyll-theme-tactile
gems:
  - jekyll-seo-tag